import 'dart:ui';

import 'package:flutter/material.dart';

class ThemeColors {
  static const Color redScreen = Color.fromRGBO(196, 29, 32, 1);
  static const Color redScreen1 = Color(0xffBC1F21);
  static const Color redScreen2 = Color.fromRGBO(102, 1, 2, 0.8);

  static const Color black = const Color(0xff000000);
  static const Color white = const Color(0xffFFFFFF);
  static const Color background = const Color(0xff1B2634);
  static const Color pokeballRedTop = const Color(0xffA51A17);
  static const Color pokeballRedBottom = const Color(0xffE51D20);
  static const Color pokeballWhiteTop = const Color(0xffFFFFFF);
  static const Color pokeballWhiteBottom = const Color(0xffA19E9E);
  static const Color screen = const Color(0xff1E1E1E);
  static const Color screnFrameInternal = Color(0xff777474);
  static const Color screenFrame = const Color(0xffDAE8EB);
  static const Color screenFrameBorder = const Color(0xffE51D20);
  static const Color screenButton = const Color(0xffE51D20);
  static const Color lampFrame = screenFrame;
  static const Color lampInner = const Color(0xff3BC4FA);
  static const Color lampOuter = const Color(0xff1778D5);
  static const Color lampShineIner = white;
  static const Color lampShineOuter = const Color(0xff3AC2F9);
  static const Color redLedInner = const Color(0xffFF9282);
  static const Color redLedOuter = const Color(0xffE0433F);
  static const Color redLedBorder = const Color(0xffBC1F21);
  static const Color yellowLedInner = const Color(0xffFEDB6A);
  static const Color yellowLedOuter = const Color(0xffFABE17);
  static const Color yellowLedBorder = const Color(0xffEA960A);
  static const Color greenLedInner = const Color(0xffBDEAA7);
  static const Color greenLedOuter = const Color(0xff52C153);
  static const Color greenLedBorder = const Color(0xff5C743A);
  static const Color bigButtonLayerBorder = Color(0xff000000);
  static const Color bigButtonLayer0Top = Color(0xff686D70);
  static const Color bigButtonLayer0Bottom = Color(0xff050F11);
  static const Color bigButtonLayer1Top = Color(0xff050F11);
  static const Color bigButtonLayer1Bottom = Color(0xff686D70);
  static const Color bigButtonLayer2Top = Color(0xff676A6F);
  static const Color bigButtonLayer2Bottom = Color(0xff242625);
  static const Color soundLayer0Top = Color(0xff7B8287);
  static const Color soundLayer0Bottom = Color(0xff324144);
  static const Color soundLayer1Top = Color(0xff4A494E);
  static const Color soundLayer1Bottom = Color(0xff525157);
  static const Color soundLayer2 = Color(0xff182022);
  static const Color digitalDirectionTopLayer0Top = Color(0xff7B8287);
  static const Color digitalDirectionTopLayer0Bottom = Color(0xff050F11);
  static const Color digitalDirectionTopLayer1Top = Color(0xff686D70);
  static const Color digitalDirectionTopLayer1Bottom = Color(0xff050F11);
  static const Color digitalDirectionTopLayer2Bottom = Color(0xff182022);
  static const Color digitalDirectionLeftLayer0Top = Color(0xff7B8287);
  static const Color digitalDirectionLeftLayer0Bottom = Color(0xff050F11);
  static const Color digitalDirectionLeftLayer1Top = Color(0xff686D70);
  static const Color digitalDirectionLeftLayer1Bottom = Color(0xff050F11);
  static const Color digitalDirectionLeftLayer2Bottom = Color(0xff182022);
  static const Color digitalDirectionBottomLayer0Top = Color(0xff7B8287);
  static const Color digitalDirectionBottomLayer0Bottom = Color(0xff050F11);
  static const Color digitalDirectionBottomLayer1Top = Color(0xff686D70);
  static const Color digitalDirectionBottomLayer1Bottom = Color(0xff050F11);
  static const Color digitalDirectionBottomLayer2Bottom = Color(0xff182022);
  static const Color digitalDirectionRightLayer0Top = Color(0xff7B8287);
  static const Color digitalDirectionRightLayer0Bottom = Color(0xff050F11);
  static const Color digitalDirectionRightLayer1Top = Color(0xff686D70);
  static const Color digitalDirectionRightLayer1Bottom = Color(0xff050F11);
  static const Color digitalDirectionRightLayer2Bottom = Color(0xff182022);

  // Region Action Buttons
  static const Color actionButtonUpTop = Color(0xff53595C);
  static const Color actionButtonUpBottom = Color(0xff363D40);
  static const Color actionButtonLeftTop = Color(0xff535A5C);
  static const Color actionButtonLeftBottom = Color(0xff363D40);
  static const Color actionButtonBottomTop = Color(0xff353D3F);
  static const Color actionButtonBottomBottom = Color(0xff182022);
  static const Color actionButtonRightTop = Color(0xff353C3F);
  static const Color actionButtonRightBottom = Color(0xff172022);
  static const Color actionButtonMiddleTop = Color(0xff353C3F);
  static const Color actionButtonMiddleBottom = Color(0xff172022);
  static const Color actionButtonCircleTop = Color(0xff444B4E);
  static const Color actionButtonCircleBottom = Color(0xff272F31);
}
