name: flutterando_class
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_modular: ^3.1.1+1
  flutter_triple: ^1.0.5+1
  flutter_svg: ^0.22.0

dev_dependencies:
  flutter_modular_test: ^1.0.1
  flutter_test:
    sdk: flutter
  triple_test: ^0.0.5

flutter:

  uses-material-design: true

  assets:
    - assets/img/books/
    - assets/img/icons/
    - assets/img/logo/
  
  fonts:
    - family: Milliard
      fonts:
        - asset: assets/fonts/milliard/Milliard-Medium.ttf
          weight: 500
        - asset: assets/fonts/milliard/Milliard-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/milliard/Milliard-Bold.ttf
          weight: 700
